### ISSUE TITLE
SDK not existent on mvnrepository.com

### ISSUE THREAD

**Issue by robson90** [unzerdev/java-sdk#13]
As seen on this Screenshot, I can't find the SDk on mvnrepository.

https://imgur.com/a/3ihkGet

**Comment by DerAusHeidelberg** [comment]
Hi @robson90,

we are currently working on the deployment for this SDK.

We will inform you as soon as we have deployed the SDK.

**Comment by sixer1182** [comment]
Dear @robson90 
this has been resolved, sorry for the long wait.
https://mvnrepository.com/artifact/com.unzer.payment/java-sdk
