### ISSUE TITLE
NullPointerException during first time loading properties

### ISSUE THREAD

**Issue by McIntozh** [unzerdev/java-sdk#18]
The bugfix for the issue (https://github.com/heidelpay/heidelpayJava/issues/100) in the old heidelpayJava SDK was not migrated to the new SDK, so the NullPointer also occurs in this library.
See
https://github.com/unzerdev/java-sdk/blob/develop/src/main/java/com/unzer/payment/service/PropertiesUtil.java
VS
https://github.com/heidelpay/heidelpayJava/blob/master/src/main/java/com/heidelpay/payment/service/PropertiesUtil.java

**Comment by DerAusHeidelberg** [comment]
Hi @McIntozh,

we are currently on it and plan to release in the near future.

Please be a little patient. We will inform you about the new release when its done.

**Comment by DerAusHeidelberg** [comment]
Hi @McIntozh,

we have now released a new version (1.1.0.1).

Bug is resolved now.
